services:
  # Message Broker: Redpanda
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092" # Accesso da localhost (host)
      - "9092:9092"   # Accesso interno alla rete Docker
      - "18081:8081"  # Schema Registry

  # Ingestion Gateway
  ingestion-gateway:
    build: ./ingestion-gateway
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BROKER=redpanda:9092
    depends_on:
      - redpanda

networks:
  default:
    name: seismic-network